# -*- coding: utf-8 -*-
"""Langchain_RAG_Example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Qpfr2KlZxCbCbUyLdonpnXqex-tLiW_
"""

!pip install -q youtube-transcript-api langchain-community faiss-cpu langchain-groq

from youtube_transcript_api import YouTubeTranscriptApi,TranscriptsDisabled
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate
from langchain.embeddings import HuggingFaceEmbeddings
from langchain_groq import ChatGroq
from google.colab import userdata

"""## Step 1a - Indexing (Document Ingestion)"""

video_id='Gfr50f6ZBvo' # only video id not the full URL

try:
  transcript_list=YouTubeTranscriptApi.get_transcript(video_id=video_id,languages=['en'])

  transcript = " ".join(chunk["text"] for chunk in transcript_list)
  print(transcript)

except TranscriptsDisabled:
    print("No captions available for this video.")

transcript_list