# -*- coding: utf-8 -*-
"""Runnable_Passthrough.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11pDcwglGL4dFcyMHfK2GS7Ji2nOlcHBZ
"""

!pip install langchain-groq
!pip install python-dotenv
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from dotenv import load_dotenv
from google.colab import userdata
from langchain.schema.runnable import RunnableSequence,RunnableParallel,RunnablePassthrough

model=ChatGroq(model_name='llama3-70b-8192',api_key=userdata.get('GROQ_API_KEY'))

prompt1=PromptTemplate(template='Generate a joke on the {topic}',
               input_variables={'topic'})

prompt2=PromptTemplate(template='explain the joke on the {text}',
               input_variables={'text'})

parser=StrOutputParser()

joke_chain=RunnableSequence(prompt1,model,parser)

parallel_chain=RunnableParallel({
    'Joke':RunnablePassthrough(),
    'Explaination':RunnableSequence(prompt2,model,parser)
})

chain=RunnableSequence(joke_chain,parallel_chain)

print(chain.invoke({'topic':'Indian premier leage'}))