# -*- coding: utf-8 -*-
"""Runnable_Parallel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-CKvQ3nNMeURAyvKi_yZG-sMW_bx8l4J
"""

!pip install langchain-groq
!pip install python-dotenv
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from dotenv import load_dotenv
from google.colab import userdata
from langchain.schema.runnable import RunnableSequence,RunnableParallel

model=ChatGroq(model_name='llama3-70b-8192',api_key=userdata.get('GROQ_API_KEY'))

tweet_prompt=PromptTemplate(template='Generate a tweet on the {topic}',
               input_variables={'topic'})

linkdn_prompt=PromptTemplate(template='Generate a linkedn post on the {topic}',
                             input_variables={'topic'})

parser=StrOutputParser()

parallel_chain=RunnableParallel({
    'tweet':RunnableSequence(tweet_prompt,model,parser),
    'linkdn':RunnableSequence(linkdn_prompt,model,parser)
})

result=parallel_chain.invoke({'topic':'Indian Cricket Team'})
print (result)
#print(result['tweet'])
#print(result['linkdn'])